### ISSUE TITLE
画像抜きAPIが謎の５枚目がついてくる

### ISSUE THREAD

**Issue by a2chub** [egroup-develop/TensorFlow#1]
バナー画像は入りません。

**Comment by camberbridge** [comment]
# 原田さんへのご報告
- 作成頂いている(API)[https://study-golang.appspot.com/input]について
  - 各アイドルの5枚目がLoGiRLのバナー画像になっていました
  - 5, 7, 9, 11番目のアイドルについては画像が6枚あって6枚目がバナーとなっています

ご確認よろしくお願い致します

**Comment by camberbridge** [comment]
ありがとうございました！
